---
title: "God, and the origin world"
author: "Fujimiya Amane"
date: "2026-02-27"
categories: [Blog, daily]
format:
  html:
    toc: true
status: "done"
confidence: "likely"
importance: 5
---

Over the time, I walked back to the past to see of the naive me, writing and pondering of those worlds outside, of the voices in such endless breath, innocent, unrefined but fiery. Such is also where I saw of which the issue that the old self happened to come across. The position on *God and such origin*. 

Specifically, what was on the table on which the monograph plays on? Perhaps, it might just be as simple as to question, 

> What makes of the anthropological origin of god. Of which of the far-away land there exists various versions of said entity, plural than singular, through the looking glass, what is the answer?

Maybe perhaps, such is a futile topic. I may have to search up the memories holding the answer. Or maybe not, as I would have to extend the essay further out. 

# The question

Toward the notion of god, we need several alignment questions to aim for before making any analysis, because such is rather so large and so ingrained into the language of natural Homo sapiens, that it would seem so natural that we will say 'oh god', and such thereof, even if it is a learned pattern than most. Thus, justification would have to be made on the baseline of *what are those questions that we answer* in certainty, or uncertain of such conclusion. This is determined, for my own method, from the nature of the dogma on divinity itself. 
