---
title: "Insufficiency, slowness"
author: "Fujimiya Amane"
date: "2026-05-27"
categories: [Blog, Daily, Life]
format:
  html:
    toc: true
description: "Or so we live of nature, for us to wait until its is downtime, or we are to struggle until the sun to set?"
status: "not yet done"
---

Disguise a gift there be, the pain being a present, of present, it can take. I have learnt this lesson for the time long gone, for the past that feels short yet a thousand years apart, of the memory fading in tandem of what there are new, of where there are fakeness, of which nevertheless put ahold. 

Encountering as math, I feel the insufficiency of myself. The world threw me into this world, knowingly so that I developed the aptitude of which I am *skeptical of brilliance*, to a finite degree where such is legible. But, does it? Will it? What there are to be certainly not normal and in such a way would be said to be of such as to be stated as received, not born with, of the path I take in life, of the time I spent on this earthen ground since when once thought. I always yearn for the skill of analytics, yet despite all efforts the only virtue I receive from the egregious effort, was nothing but futile expert, of which bears no resemblance to the sparks and fire I see from afar, yet unable to reach in due time. While people spending time surging through mathematical precisions and formalism, all I saw are fears in myself - of the formalism I don't fully catch on, of those I took times to develop and mature, of those I swear of myself in my memory comes forth of the past there are, that I am in itself, of the fiery wind in life, never be able to see down on those words and technicals, of which I never inner of the crowd, but forever outward, stepping inside just a bit. There, is what I do. To be skeptical of formalism. To be skeptical of languages. To know, that language, representations are *imperfect*, are *hard*, excruciatingly hard, and they are never the real thing. To know, that for many things I cannot do enough of, of the words never to be spoken of because it bears no terms worthy of such, that I question, regardless of good or bad, of the notion to be put down. Because, of my own insufficiency in reading those, I am to dig down onto their foundations, and to trace back their own logia, of their own falecia in enlightenment, where they be to get those, of which assumptions take so bold, of what conjures their mind, what to forget, what to take, what to pay, what to be due. Those are what I did. 

What am I today? Of the failure that shaped me, of the insufficiency bred what to be *me*? Or it is the thin line to the other face, of which it is the capacity to be skeptical, of *conceptual understanding*, of the refusal to *bog down to details*, for I know if I ever bog down to such it would be illuminating of the eye, yet misstate of the mind to see of a single shard? Of the workaround of my own limited mortal soul, for it to never shining so bright as those faraway candles in the darkness, yet keeps burning, to the end of those pillars, of where everything starts? I don't have a clue. What to know, however, is that, whether it is worth it or not. Be sure it is, one can say. Be sure it arrogance, one might speak. Nevertheless, it gives me the forever grateful position that I can take on, so profound, so simple, so elegant, yet so crude, so aggressive, so forceful. To be skeptical of anything, and to grievously take everything for yourself, to ask questions of those inside the curtain will not ask, of those ideas no one will think of, because, they are to be entrenched of their own domain, of the peak where the Olympus Mons to be, thus they never seek another peak. Such certainty, such profound illumination. Rejection of self from those places, I yet to find another way to live and work. 

It is not without its mileage of what to be disadvantaged of. I surely have been isolated or at least vindicated of truthfulness, yet never accepted awhole. I find everything to be in the middle, for my principle in those terms to be of *tension*, for it to hold both or more, for no positions are to be outright correct, for anything to be rather leaned but never fully, of which I bear in mind of my own limitation and mortality, of the two eyes yet knowing there are millions shades. I belong to nowhere, yet also familiar to everywhere. What are those feeling, one can ask? It shall be of time, I figured, and the record will show for itself. Nor it be elegant, in search of the crudeness near the ground at most, in need of the elegance making up of beauty, what to be wanted. Perhaps, after all, crudeness has its own elegance of such for itself verily so painted - of the foremost excavation, those worth more than golds, far glamorous than the made-up towers. 

Same question, same breath. I am to ask of the following. Are we there, living as human, of legs, of eyes, of hands, of ears, of mouth, of nose. To spread your hand and touch what there is of this world. To traverse what it be on this land. To see, of the wonder where we are. To smell of the fragrant motions, to hear of the sound this world in optics to make, to move, to keep on, to live, to be there without you. For it to be experienced of those we are to live in it? Of which those are capacities are there be blessing of nature befall on us? Or, should we are to live in fear, to which acknowledge the gifts, yet fearing every day that those will be lost to time, to the spiral of degradation that seed new lives, of the wonder now you cannot see but memories of the land you have forgotten? What are we, to struggle against the throwness, or to be dwelt within it, following course of what there be, until the end of time? 

The last question, for what it is worth it to be spoken of. What are we to this world? Of the unfairness being thrown in. For what said of disadvantaged there is. Of the fear, as I feared, of myself, to mistake, of the failure too costly to bear. What are we in this world, of which the hammer thrown already, for the match already started, we are to participate, the cake has been shared, the water dirtied, the goal scattered, the truth in fade? What are we to make ourselves in this world, forget of the man with their fake hands, of the God created out of glorious purpose, for it to be what to cling on? What if I am not to cling on those false hopes, to keep moving on, to keep what left of my dignity, to aim far, to aim wide, to accept failures, of which it destroys part of me, to know that I have ever tried? What, is in the end of the road? To know this, is wisdom of million years. Such shall be the answer, such shall be the blasphemous path. However wicked it be, only the temporal might rest judgment of what is wrong, or right. Perhaps that is what said to be of existentialism are there to teach us. No matter what there is, we are formed by our birth, of the situated being without permission, of the orphan never wished to be born, of the child out of wedlock, distasted of their own parents. Of the creation, for Cantor to be hated for bringing infinitude to this world of the questions those on the mountain can never descent above, yet for him to also claim of the Ars Magna, of the ground unjustified there is. What to make of us ourselves will be *our lives*, and as long as that stands, there is no God to be filled of destiny. Make us our own Gods, and let it be whatever paths it takes, for there be no binary, for there be no gracious god. Pay attention to the path. Make it due. 

Struggle until the dawn of sun. 



