---
title: "The map and the math"
author: "Fujimiya Amane"
date: "2025-12-11"
categories: [Blog, philosophy, math]
format:
  html:
    toc: true
description: "Just a thought"
status: "done"
confidence: "likely"
importance: 5
---

What, to be of mathematics? 

Where life is chaotic as it is, in which we are of the flesh and meat, observe and feel life with eyes and ears, or feeling and touches, we inherently develop what to make sense of such, particularly painful of time, yet beautiful and perhaps deceptive. That is why we resorted to create the language of mathematics, of which the first ever action in the history of such is to struct barebone, stripping down the physical epiphany of what to observe of. Such is then also abstraction, and thus the undeniably deceptive, beautiful, incomprehensible beauty of such language breathen forth onto human as it is. But so is the perception, incomplete, inconsistent as once Gödel brought down the Icarus's wing of the total theory, our maths is simply, forgotten of its origin, a model. A model of reality so effective, that our mortality believes in its ability to explain, as to be the map on which the landscape can be deceptively naive of the observant. So is what I want to say of the theory of modelling, to be the main central line in which I am also developing anew, lest of the arrogance to quicken myself of pace toward the great shoulder of the old age. Where we are stuck of interpretation. Perhaps we need a shift in focus.

Toward such, what gives? Why is mathematics rather descriptive? Such question can be answered not through logic or arguments but through history, where one knows of arithmetics but not group theory, where knowledges were articulated of geometry in simple terms, of the Euclidean or else in different corners of the ancient worlds, full of mystery from the far-away land on which every single thinkers of the time, distances apart, converge to a singular description. Thus is the descriptive nature of mathematics, born out of its primitive form as a tool, a tool of which taken forth by those same people to describe what cannot be done otherwise, of the restraints in which have to be resolved, of the imagination that strips physical limitation altogether in its first grand step, where one can imagine the utopia of a million apples, instead of such a handful basket. So is the abstraction at first layer. We often forget such virtue. 

Grateful of such, mathematics then can also be realized to be not so objective as it is. Similar to those sketches should be available of this page (or rather blog post sections), one can indeed see that we have no clue, lest of no guarantee, that the world is static, that our views are invariant of changes or indeed being global and baseline as it is. For it to be relative, of which the anthropology of humanity forces upon itself, so is that mathematics is a construct of human, it bears marks of such limitation and flesh and soul. Sometimes, lamenting is possible, then *abstraction* is the most powerful tool, but also the most arcane and unintelligible one of our arsenal. Such is to say no one understand infinity - many claims of such, but none - not even seasoned mathematicians, can do that, simply because we cannot fathom the scale in which adding more zeros moves the entirety of the meaning, or the scale in which we are not familiar of. So is continuity, so is discrete and continuous, and many more. 

That is not to say we cannot try. Not to say we are useless, but rather it is to say the Everest is forever high, but if one did not dare to climb the first step, one should be ashamed to not try, rather than try and slip. A painful lesson, a slippage, is better than never to climb the Tower of Babel. Participating in its collapse is, in a sense, a beautiful thing. 