---
title: "Is it really no free lunch?"
bibliography: "ref1.bib"
author: "Fujimiya Amane"
date: "2025-09-27"
categories: [Blog, machine learning]
format:
  html:
    toc: true
description: "An inquiry of the basic concept that contradicts the universality objective of learning theory. The article is imcomplete by the way"
status: "not yet done"
---

Of anything, we are typically concerned of creating a universal framework - for example, in a meeting of which we require the unification of voices and resolution; of mathematics where category theory and a lot of others try to unify mathematics under the singular lens; or in physics, there exists the quest for the theory of universal physical law, of which the standard model almost, almost claims such title in the process. The same is true for learning theory. Specifically, it is the question as to ask, "Will there ever be a universal learner $\mathcal{L}$ that will be able to approximate everything, to a given degree of correctness?". The villain in such story, is then, the **no-free-lunch** theorem. (see [@980896], [@wolpert1997no], and [@wolpert2005coevolutionary]).

# Understanding no-free-lunch

No-free-lunch on itself is a troublesome notion requiring understanding of sort. Okay, well, let's go from the beginning, shall we? 
