---
title: "Overconfidence, Liability"
author: "Fujimiya Amane"
date: "2023-10-02"
categories: [Blogs, daily]
format:
  html:
    toc: true
status: "wip"
confidence: "likely"
importance: 5
---
Today... This will be a 3-day note, it seems.


___
### QOTD (Question of the day)

- Luminiferous Aether is proposed to be a medium which allows lights to move inside vacuum spaces. It is not proved wrong ever since, though. But what is the correct resolution to this. Can QFT or just classical field theory stands in and pertains to this properties?
- Quantum functions is weird, isn't it?
- Are all law of physics basically a construct? In a sense of the interaction construct, same as algebraic structure
- What is the possible way for a ball to fly in a isolated system with controlled all direction winds? Topologically, can a footballer go through a setup of 7 defenders without having a closed loop?

___
### TOTD (Thoughts of the day)

Nothing much. As far as the history of human is concerned, not yet. 

Otherwise, we will just be a dust till down. The society shaped us deeply, engraving inside us the class system that is deemed too hard to break apart.  
#### References
