---
title: "Oh, the forbade antic"
author: "Fujimiya Amane"
date: "2025-12-11"
categories: [Blog, daily]
format:
  html:
    toc: true
status: "done"
confidence: "likely"
importance: 5
---

It is a quiet day, of a solemn morning. 

I resided in the corner, or rather around the ring of people, sat down of my indictment, to learn of this unbearable class on 'soft skill', in this barren location ones calls university. 

"Oh! How *painful it is* to catch eyes again with whom I hate.". Or so I thought, here comes the teacher I despise, of the arrogance she was showing, or the berating wisdom worth no pennies on the pavement. Of the inculcation with destitute that normal people do not understand, though such is also my arrogance.


She said, of emotion! Of what is to be life. Of what to make of emotion of human. Of the reverent position as it is of human to ourselves. I was enraged. Not because of the question? But of the form that it was asked. Like a senior without wisdom, of a person diluted themselves in the fantasy once never forget, to forge them of the worldview! 

And think themselves as the holder of knowledge superior of others, unknowingly a grain of sand in the rough ocean. 

Then it comes, just as every cadence of a ballet, the drama yet one awaits - I was called. 

So is my rage partially gone, pave way for thoughts. What can be of it?

Poem. Of course, it is. Oh captain, my captain, you will be missed. Your soul is what enriched human of what there is. To make forth of what to live! Not the unbearable pain without relief. 

Of which we live as to be the human race, like Keating once told upon which thousands of souls listened. But no more. Of which we see and live as the human we strive to be!

I spoke out loud.

But oh no! I can't transpire such notion to those faces unfamiliar of such thoughts. Of those who do not respect the other, of the blinding conceit of the breathen told. They forced me to sing a poem, like posited of the king on the high horse, needing the entertainment of the peasant. 

I don't sing, I write. I don't talk, but raise the pen and let the pages cry out for those emotions that cannot be expressed through futile words, of the uncivilized notion verbalized of convenience.  

My words are my strength, my pen the sword, of my voice insufficient of perspective, to cry out loud those rhythm ones pervade. 

So is myself incapable of transpire such. And so is a fool as is. Ah, what have I done of myself. 

What a humiliating end.

No one to believe in. Those I call friend talk of it as foolish. Ridicule to the basic reaction. Thence such shallow depth, hiding in laughter, loud jokes, and deceptive insecurity vibrated of every verse. 

What to be of them?

There perhaps it lies of the truth. That for ones' soul, thence my live of itself. 

> Let there be light. Let there be night.
> For insights never fade,
> of the endless inquiry daylight never settles,
> of the human thirst for knowledge,
> impure yet beautiful,
> serves as to live what there is.