---
title: "Vini, Viti ,Vinci. Le Champagne"
author: "Fujimiya Amane"
date: "2023-09-06"
categories: [Blogs, daily]
format:
  html:
    toc: true
status: "wip"
confidence: "likely"
importance: 5
---
The title is a bit confusing as heck but whatever. 

### QOTD (Question of the day)

- Living in a world of 3 dimensions, the world of a greater, 4D space is much more difficult to understand. Perhaps because we are encapsulated in our own 3D existence, which might be pseudo-science, but mathematically correct functions and statements are our only thing to stick our heads on it. But this beg a few question, of which one is biggest: can we try to 'extend' the fourth dimension? According to topology the world seems to have 12 dimensions or so, but all but the first 3 are so small that the spatial dimensions only contain mostly 3 dimensions. Thus if we 'bend' them, then, what could possibly be it? 
- Can there be simultaneous execution of different control flows, for different execution streams in C++. 

### TOTD (Thoughts of the day)

I have nothing to talk about. Except, perhaps, the fact that many people still do not know of the differences between stock and share, bond and dividend. That including me in the past, too,