---
title: "The circular notions of things"
author: "Fujimiya Amane"
date: "2025-04-20"
categories: [Blogs, daily]
format:
  html:
    toc: true
description: "After a while of using Newtonian formalism for physics, many saw its disadvantages and the cumbersome tasks of making it work for dynamically complex system. Fortuntately, someone indeed stood up and gives us the $\\mathcal{L}$: the Lagrangian."
status: "wip"
confidence: "likely"
importance: 5
---
Alright. Got some motivation today. Also successfully done the circuit with 2 consecutive blinking light bulbs, controlled from a main control Arduino with port 9 and 7 as OUTPUT, and output signal (actually electrical voltage). So yeah, cool stuff. 


___
### QOTD (Question of the day)
- Why when light is stretched - or with long lights in scope, we magnified the image? What is happening here?
- Now I am actually wonder what control the lighting of TV - where the circuit is put into service without "wired" stuff inside? It seems weird because it used LED, but the control is nowhere to be found. And the theory of light combination is not good - too chaotic for a consistent performance.
- Why an electron being slowed down lead to the release of photons in different wavelengths?




___
### TOTD (Thoughts of the day)
I hate school. Pretty much.

